import pytest
import numpy as np
import shutil
import platform
import ion_flux as fx
from ion_flux.runtime.engine import Engine
from ion_flux.compiler._3_optimization.sparsity_tracer import SparsityAnalyzer
import math
import sys
import os

# Add the 'models' directory to the path so we can import the models
sys.path.append(os.path.join(os.path.dirname(__file__), '../..', 'models'))

from Chen2020_DFN import Chen2020_DFN
# from Marquis2019_1Plus1D_SPMe import Marquis1Plus1D_SPMe
from ORegan2022_ThermalDFN import ThermalDFN


def _has_compiler() -> bool:
    has_std = bool(shutil.which("clang++") or shutil.which("g++"))
    has_mac = platform.system() == "darwin" and (
        shutil.os.path.exists("/opt/homebrew/opt/llvm/bin/clang++") or 
        shutil.os.path.exists("/usr/local/opt/llvm/bin/clang++")
    )
    return has_std or has_mac

REQUIRES_COMPILER = pytest.mark.skipif(not _has_compiler(), reason="Requires native C++ toolchain.")


def get_missing_dependencies(model):
    engine = Engine(model=model, target="cpu", mock_execution=False)
    N = engine.layout.n_states
    
    # 1. Reconstruct the MIR-derived sparsity pattern directly from the Engine's cache
    _, _, c_rows, c_cols, c_dense = engine._cpr_cache
    
    python_set = set(zip(c_rows, c_cols))
    
    # Expand dense Arrowhead rows into the sparse set for comparison
    for r in c_dense:
        for c in range(N):
            python_set.add((r, c))
            
    # 2. Reconstruct the actual dense C++ Jacobian via Native Evaluation
    # Randomize inputs to ensure no structural zero is accidentally 
    # hidden by mathematical coincidences (e.g. 0.0 * gradient)
    np.random.seed(42)
    y = np.random.uniform(0.1, 1.0, N)
    ydot = np.random.uniform(0.1, 1.0, N)
    
    J_dense = np.array(engine.evaluate_jacobian(y.tolist(), ydot.tolist(), c_j=1.0, parameters={}))
    
    # 3. Extract exact numerical non-zero tuples generated by the Enzyme LLVM plugin
    enzyme_rows, enzyme_cols = np.where(np.abs(J_dense) > 1e-12)
    enzyme_set = set(zip(enzyme_rows, enzyme_cols))
    
    # 4. Assert the MIR grapher is a strict, safe superset of the numerical reality
    return enzyme_set - python_set



@REQUIRES_COMPILER
def test_static_sparsity_analyzer_matches_enzyme_oracl_v1():
    """
    PROBE: Proves that the Python AST Tracing algorithm computes a safe structural 
    superset of the Jacobian compared to the mathematically exact C++ Enzyme evaluation.
    This guarantees no loss of mathematical coupling when the C++ code generator is gutted 
    for CPR/Forward-Mode AD.
    """
    missing_dependencies = get_missing_dependencies(model=Chen2020_DFN())
    assert not missing_dependencies, \
        f"FATAL: Python analyzer failed to map physical dependencies! " \
        f"It missed {len(missing_dependencies)} cross-couplings. Examples: {list(missing_dependencies)[:5]}"



@REQUIRES_COMPILER
@pytest.mark.skip(reason="Passes, but takes a long time to run")
def test_static_sparsity_analyzer_matches_enzyme_oracl_v2():

    missing_dependencies = get_missing_dependencies(model=ThermalDFN())
    assert not missing_dependencies, \
        f"FATAL: Python analyzer failed to map physical dependencies! " \
        f"It missed {len(missing_dependencies)} cross-couplings. Examples: {list(missing_dependencies)[:5]}"



@REQUIRES_COMPILER
@pytest.mark.skip(reason="Disabled Marquis model")
def test_static_sparsity_analyzer_matches_enzyme_oracl_v3():

    missing_dependencies = get_missing_dependencies(model=Marquis1Plus1D_SPMe())
    assert not missing_dependencies, \
        f"FATAL: Python analyzer failed to map physical dependencies! " \
        f"It missed {len(missing_dependencies)} cross-couplings. Examples: {list(missing_dependencies)[:5]}"


if __name__ == "__main__":
    pytest.main(["-v", "-s", __file__])