"""
Backend Compilation: Enzyme Automatic Differentiation

Validates LLVM-level reverse/forward-mode autodiff generated by Enzyme, ensuring
exact analytical Jacobians across smooth math, piecewise functions, and triggers.
"""

import pytest
import shutil
import platform
import numpy as np
import ion_flux as fx
from ion_flux import Engine
from ion_flux.compiler.invocation import NativeCompiler

# --- Environment Checks ---
def _has_compiler() -> bool:
    has_std = bool(shutil.which("clang++") or shutil.which("g++"))
    has_mac = platform.system() == "darwin" and (
        shutil.os.path.exists("/opt/homebrew/opt/llvm/bin/clang++") or 
        shutil.os.path.exists("/usr/local/opt/llvm/bin/clang++")
    )
    return has_std or has_mac

def _has_enzyme() -> bool:
    return bool(NativeCompiler().enzyme_plugin)


# --- Helper Methods ---
def approx_jacobian(engine: Engine, y: list, ydot: list, p: dict, c_j: float, eps: float = 1e-8) -> np.ndarray:
    """
    Computes the numerical Jacobian using central finite differences.
    For an implicit solver, the residual mapping is F(y, ydot).
    J = dF/dy + c_j * dF/dydot
    """
    N = len(y)
    J = np.zeros((N, N))
    
    for col in range(N):
        y_fwd, ydot_fwd = list(y), list(ydot)
        y_bwd, ydot_bwd = list(y), list(ydot)
        
        y_fwd[col] += eps
        ydot_fwd[col] += eps * c_j
        
        y_bwd[col] -= eps
        ydot_bwd[col] -= eps * c_j
        
        res_fwd = engine.evaluate_residual(y_fwd, ydot_fwd, parameters=p)
        res_bwd = engine.evaluate_residual(y_bwd, ydot_bwd, parameters=p)
        
        for row in range(N):
            J[row, col] = (res_fwd[row] - res_bwd[row]) / (2 * eps)
            
    return J


# --- Test Models ---
class SmoothMathPDE(fx.PDE):
    y0 = fx.State()
    y1 = fx.State()
    p_scale = fx.Parameter(default=2.0)
    
    def math(self):
        return {
            "global": [
                fx.dt(self.y0) == fx.sin(self.y0) * fx.exp(self.y1),
                self.y1 == fx.log(self.y0) - fx.cos(self.y1 * self.p_scale)
            ]
        }

class PiecewisePDE(fx.PDE):
    y0 = fx.State()
    y1 = fx.State()
    p_limit = fx.Parameter(default=1.0)
    
    def math(self):
        return {
            "global": [
                fx.dt(self.y0) == fx.abs(self.y0),
                self.y1 == fx.max(self.y0, self.p_limit) + fx.min(self.y1, 0.0)
            ]
        }

class StepLogicPDE(fx.PDE):
    y0 = fx.State()
    p_thresh = fx.Parameter(default=2.5)
    
    def math(self):
        trigger = self.y0 > self.p_thresh
        return {
            "global": [
                fx.dt(self.y0) == trigger * self.y0
            ]
        }


# --- Test Cases ---

@pytest.mark.skipif(not _has_compiler() or not _has_enzyme(), reason="Requires native AD compiler toolchain.")
def test_ad_smooth_functions():
    engine = Engine(model=SmoothMathPDE(), target="cpu", mock_execution=False)
    
    y = [2.0, 0.5]
    ydot = [0.1, 0.0]
    p = {"p_scale": 1.5}
    c_j = 10.0 # Standard inverse time-step factor
    
    jac_analytical = np.array(engine.evaluate_jacobian(y, ydot, c_j, parameters=p))
    jac_numerical = approx_jacobian(engine, y, ydot, p, c_j)
    
    np.testing.assert_allclose(jac_analytical, jac_numerical, rtol=1e-5, atol=1e-6)


@pytest.mark.skipif(not _has_compiler() or not _has_enzyme(), reason="Requires native AD compiler toolchain.")
def test_ad_piecewise_kinks_and_smooth_regions():
    """
    Validates Enzyme behavior on non-differentiable boundaries.
    """
    engine = Engine(model=PiecewisePDE(), target="cpu", mock_execution=False)
    p = {"p_limit": 1.0}
    c_j = 10.0
    
    # Region 1: Smooth logic (y0 > 0, y0 > limit, y1 < 0)
    y_smooth = [2.0, -1.0]
    jac_ana_1 = np.array(engine.evaluate_jacobian(y_smooth, [1.0, 0.0], c_j, parameters=p))
    jac_num_1 = approx_jacobian(engine, y_smooth, [1.0, 0.0], p, c_j)
    np.testing.assert_allclose(jac_ana_1, jac_num_1, rtol=1e-5, atol=1e-6)
    
    # Region 2: The Singularity (y0 = 0.0 for abs(), y0 = 1.0 for max())
    # Numerical FD fails or yields 0.5 exactly at kinks. 
    # AD intrinsically generates a valid subgradient (often 0 or 1 depending on the LLVM libc).
    # The requirement here isn't mathematical perfection (which doesn't exist at a kink), 
    # but rather that the engine doesn't produce NaN or segfault.
    y_kink = [0.0, 1.0]
    jac_ana_kink = np.array(engine.evaluate_jacobian(y_kink, [0.0, 0.0], c_j, parameters=p))
    
    assert not np.isnan(jac_ana_kink).any()
    assert np.isfinite(jac_ana_kink).all()
    # At y0 = 0, d(abs)/dy0 is subgradient. Let's ensure it exists.
    assert jac_ana_kink[0, 0] in (c_j, c_j - 1.0, c_j + 1.0, c_j - 0.0)


@pytest.mark.skipif(not _has_compiler() or not _has_enzyme(), reason="Requires native AD compiler toolchain.")
def test_ad_step_logic_relational_operators():
    """
    Validates that boolean triggers (which cast to 1.0 or 0.0) properly clear gradients
    when inactive, and pass gradients when active, acting as mathematical Heavyside functions.
    """
    engine = Engine(model=StepLogicPDE(), target="cpu", mock_execution=False)
    p = {"p_thresh": 2.5}
    c_j = 5.0
    
    # Region 1: Active (y0 = 3.0 > 2.5) -> Eq: ydot = 1.0 * y0
    # J_00 = c_j * d/dydot(ydot) + d/dy0(ydot - y0) = c_j * 1 + (-1)
    y_active = [3.0]
    jac_active = np.array(engine.evaluate_jacobian(y_active, [1.0], c_j, parameters=p))
    assert jac_active[0, 0] == pytest.approx(c_j - 1.0, rel=1e-5)
    
    # Region 2: Inactive (y0 = 1.0 < 2.5) -> Eq: ydot = 0.0 * y0
    # J_00 = c_j * 1 + d/dy0(ydot - 0) = c_j
    y_inactive = [1.0]
    jac_inactive = np.array(engine.evaluate_jacobian(y_inactive, [0.0], c_j, parameters=p))
    assert jac_inactive[0, 0] == pytest.approx(c_j, rel=1e-5)