"""
Compiler Bug Oracle: Composite Domain Coordinate Broadcasting

This suite explicitly isolates the coordinate broadcasting bug identified in the 
1+1D SPMe and DFN models. It proves that when `domain.coords` is evaluated 
inside a composite domain (which the compiler flattens into a 1D C-array), 
the compiler incorrectly multiplies the *flat global index* by `dx` rather than 
applying the necessary modulo/division operators to extract the local dimensional index.

This test asserts the exact mathematical truth. It will FAIL under the current 
compiler architecture, producing wildly out-of-bounds coordinates (e.g., treating 
a 2D grid as a single infinitely long 1D line).
"""

import pytest
import numpy as np
import shutil
import platform
import ion_flux as fx
from ion_flux.runtime.engine import Engine

# ==============================================================================
# Environment Setup
# ==============================================================================

def _has_compiler() -> bool:
    has_std = bool(shutil.which("clang++") or shutil.which("g++"))
    has_mac = platform.system() == "darwin" and (
        shutil.os.path.exists("/opt/homebrew/opt/llvm/bin/clang++") or 
        shutil.os.path.exists("/usr/local/opt/llvm/bin/clang++")
    )
    return has_std or has_mac

REQUIRES_COMPILER = pytest.mark.skipif(
    not _has_compiler(), 
    reason="Requires native C++ toolchain to evaluate AST C-array bounds."
)

# ==============================================================================
# Bug Isolation Model
# ==============================================================================

class CompositeCoordsOracle(fx.PDE):
    """
    Manufactures a 2D composite domain with highly predictable integer coordinates.
    - Outer Domain (y): bounds=(0, 2), resolution=3  --> dx_y = 1.0. Coords: [0, 1, 2]
    - Inner Domain (x): bounds=(0, 3), resolution=4  --> dx_x = 1.0. Coords: [0, 1, 2, 3]
    
    The composite domain (y * x) flattens into an array of size 12.
    Indices: 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11
    """
    dom_y = fx.Domain(bounds=(0, 2.0), resolution=3, name="dom_y")
    dom_x = fx.Domain(bounds=(0, 3.0), resolution=4, name="dom_x")
    
    comp_domain = dom_y * dom_x
    
    # Track the coordinates of the inner and outer dimensions independently
    c_inner_coords = fx.State(domain=comp_domain, name="c_inner_coords")
    c_outer_coords = fx.State(domain=comp_domain, name="c_outer_coords")

    def math(self):
        return {
            "equations": {
                # dt(c) = coords. Evaluated at y=0, ydot=0, the residual F = ydot - rhs = -coords
                self.c_inner_coords: fx.dt(self.c_inner_coords) == self.dom_x.coords,
                self.c_outer_coords: fx.dt(self.c_outer_coords) == self.dom_y.coords
            },
            "boundaries": {},
            "initial_conditions": {
                self.c_inner_coords: 0.0,
                self.c_outer_coords: 0.0
            }
        }

# ==============================================================================
# The Test
# ==============================================================================

@REQUIRES_COMPILER
def test_composite_coords_broadcasting_bug():
    """
    PROBE: Evaluates the instantaneous coordinate maps generated by the AST compiler.
    If the bug is present, the compiler evaluates `flat_index * dx`, resulting in 
    both arrays reading `[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]`.
    """
    engine = Engine(model=CompositeCoordsOracle(), target="cpu", mock_execution=False)
    
    # Extract metadata and create zeroed state arrays
    N = engine.layout.n_states
    y = np.zeros(N).tolist()
    ydot = np.zeros(N).tolist()
    
    # Evaluate the instantaneous residual
    res = engine.evaluate_residual(y, ydot, parameters={})
    
    off_inner, size_inner = engine.layout.state_offsets["c_inner_coords"]
    off_outer, size_outer = engine.layout.state_offsets["c_outer_coords"]
    
    # Because F = ydot - rhs = 0 - coords, the evaluated coordinates are -F
    simulated_inner = -np.array(res[off_inner : off_inner + size_inner])
    simulated_outer = -np.array(res[off_outer : off_outer + size_outer])
    
    # --- Exact Mathematical Truth ---
    # Inner dimension (x) cycles rapidly: 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3
    expected_inner = np.array([0., 1., 2., 3., 0., 1., 2., 3., 0., 1., 2., 3.])
    
    # Outer dimension (y) cycles slowly: 0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2
    expected_outer = np.array([0., 0., 0., 0., 1., 1., 1., 1., 2., 2., 2., 2.])
    
    # 1. Assert Inner Coordinate Broadcasting
    np.testing.assert_allclose(
        simulated_inner, expected_inner, atol=1e-12,
        err_msg=f"\nBUG DETECTED (Inner Coords): The AST compiler failed to apply the modulo operator "
                f"`(i % res) * dx` for the inner composite dimension.\n"
                f"Expected: {expected_inner}\n"
                f"Got:      {simulated_inner}\n"
                f"This causes severe unphysical scaling in models like the 1+1D SPMe!"
    )
    
    # 2. Assert Outer Coordinate Broadcasting
    np.testing.assert_allclose(
        simulated_outer, expected_outer, atol=1e-12,
        err_msg=f"\nBUG DETECTED (Outer Coords): The AST compiler failed to apply the division operator "
                f"`(i / inner_res) * dx` for the outer composite dimension.\n"
                f"Expected: {expected_outer}\n"
                f"Got:      {simulated_outer}\n"
    )

if __name__ == "__main__":
    pytest.main(["-v", "-s", __file__])