pub mod linalg;
pub mod integrator;
pub mod session;
pub mod adjoint;
pub mod bindings;

use std::os::raw::c_double;

// Native C-ABI Signatures generated by Clang/Enzyme
pub type NativeResFn = unsafe extern "C" fn(*const c_double, *const c_double, *const c_double, *mut c_double);
pub type NativeJacFn = unsafe extern "C" fn(*const c_double, *const c_double, *const c_double, c_double, *mut c_double);
pub type NativeJvpFn = unsafe extern "C" fn(*const c_double, *const c_double, *const c_double, c_double, *const c_double, *mut c_double);

// 7-argument VJP supports Matrix-Free Adjoints by returning dy_out and dydot_out
pub type NativeVjpFn = unsafe extern "C" fn(*const c_double, *const c_double, *const c_double, *const c_double, *mut c_double, *mut c_double, *mut c_double);