import ctypes
from typing import List, Tuple

class NativeRuntime:
    """Wrapper around the C-ABI shared library generated by the JIT compiler."""
    def __init__(self, lib_path: str, n_states: int):
        self.lib_path = lib_path
        self.n_states = n_states
        
        try:
            self.dll = ctypes.CDLL(lib_path)
        except OSError as e:
            raise RuntimeError(f"Failed to load compiled binary at {lib_path}: {e}")

        if hasattr(self.dll, "set_spatial_threads"):
            self.dll.set_spatial_threads.argtypes = [ctypes.c_int]
            self.dll.set_spatial_threads.restype = None

        self.dll.evaluate_residual.argtypes = [
            ctypes.POINTER(ctypes.c_double), ctypes.POINTER(ctypes.c_double),
            ctypes.POINTER(ctypes.c_double), ctypes.POINTER(ctypes.c_double),
            ctypes.POINTER(ctypes.c_double),
        ]
        self.dll.evaluate_residual.restype = None
        
        if hasattr(self.dll, "evaluate_observables"):
            self.dll.evaluate_observables.argtypes = [
                ctypes.POINTER(ctypes.c_double), ctypes.POINTER(ctypes.c_double),
                ctypes.POINTER(ctypes.c_double), ctypes.POINTER(ctypes.c_double),
                ctypes.POINTER(ctypes.c_double),
            ]
            self.dll.evaluate_observables.restype = None

        if hasattr(self.dll, "evaluate_jvp"):
            self.dll.evaluate_jvp.argtypes = [
                ctypes.POINTER(ctypes.c_double), ctypes.POINTER(ctypes.c_double),
                ctypes.POINTER(ctypes.c_double), ctypes.POINTER(ctypes.c_double),
                ctypes.c_double, ctypes.POINTER(ctypes.c_double), ctypes.POINTER(ctypes.c_double)
            ]
            self.dll.evaluate_jvp.restype = None

        self.dll.evaluate_vjp.argtypes = [
            ctypes.POINTER(ctypes.c_double), ctypes.POINTER(ctypes.c_double),
            ctypes.POINTER(ctypes.c_double), ctypes.POINTER(ctypes.c_double),
            ctypes.POINTER(ctypes.c_double), ctypes.POINTER(ctypes.c_double),
            ctypes.POINTER(ctypes.c_double), ctypes.POINTER(ctypes.c_double),
        ]
        self.dll.evaluate_vjp.restype = None

    def set_spatial_threads(self, num_threads: int) -> None:
        if hasattr(self.dll, "set_spatial_threads"):
            self.dll.set_spatial_threads(num_threads)

    def evaluate_jvp(self, y: List[float], ydot: List[float], p: List[float], m: List[float], c_j: float, v: List[float]) -> List[float]:
        y_arr = (ctypes.c_double * self.n_states)(*y)
        ydot_arr = (ctypes.c_double * self.n_states)(*ydot)
        p_arr = (ctypes.c_double * len(p))(*p)
        m_arr = (ctypes.c_double * len(m))(*m)
        v_arr = (ctypes.c_double * self.n_states)(*v)
        out_arr = (ctypes.c_double * self.n_states)()
        
        if hasattr(self.dll, "evaluate_jvp"):
            self.dll.evaluate_jvp(y_arr, ydot_arr, p_arr, m_arr, ctypes.c_double(c_j), v_arr, out_arr)
        return list(out_arr)

    def evaluate_vjp(self, y: List[float], ydot: List[float], p: List[float], m: List[float], lambda_vec: List[float]) -> Tuple[List[float], List[float], List[float]]:
        y_arr = (ctypes.c_double * self.n_states)(*y)
        ydot_arr = (ctypes.c_double * self.n_states)(*ydot)
        p_arr = (ctypes.c_double * len(p))(*p)
        m_arr = (ctypes.c_double * len(m))(*m)
        lam_arr = (ctypes.c_double * self.n_states)(*lambda_vec)
        
        dp_out = (ctypes.c_double * len(p))()
        dy_out = (ctypes.c_double * self.n_states)()
        dydot_out = (ctypes.c_double * self.n_states)()
        
        self.dll.evaluate_vjp(y_arr, ydot_arr, p_arr, m_arr, lam_arr, dp_out, dy_out, dydot_out)
        return list(dp_out), list(dy_out), list(dydot_out)

    def evaluate_residual(self, y: List[float], ydot: List[float], p: List[float], m: List[float]) -> List[float]:
        y_arr = (ctypes.c_double * self.n_states)(*y)
        ydot_arr = (ctypes.c_double * self.n_states)(*ydot)
        p_arr = (ctypes.c_double * len(p))(*p)
        m_arr = (ctypes.c_double * len(m))(*m)
        res_arr = (ctypes.c_double * self.n_states)()
        
        self.dll.evaluate_residual(y_arr, ydot_arr, p_arr, m_arr, res_arr)
        return list(res_arr)
        
    def evaluate_observables(self, y: List[float], ydot: List[float], p: List[float], m: List[float], n_obs: int) -> List[float]:
        y_arr = (ctypes.c_double * self.n_states)(*y)
        ydot_arr = (ctypes.c_double * self.n_states)(*ydot)
        p_arr = (ctypes.c_double * len(p))(*p)
        m_arr = (ctypes.c_double * len(m))(*m)
        obs_arr = (ctypes.c_double * n_obs)()
        
        if hasattr(self.dll, "evaluate_observables"):
            self.dll.evaluate_observables(y_arr, ydot_arr, p_arr, m_arr, obs_arr)
        return list(obs_arr)