import os
import sys
import glob
import ctypes
import hashlib
import subprocess
import shutil
import logging
import tempfile
from typing import List

logger = logging.getLogger(__name__)

class NativeRuntime:
    """Wrapper around the C-ABI shared library generated by the JIT compiler."""
    def __init__(self, lib_path: str, n_states: int):
        self.lib_path = lib_path
        self.n_states = n_states
        
        try:
            self.dll = ctypes.CDLL(lib_path)
        except OSError as e:
            raise RuntimeError(f"Failed to load compiled binary at {lib_path}: {e}")

        # Syncing all signatures to include the new 'm' array
        self.dll.evaluate_residual.argtypes = [
            ctypes.POINTER(ctypes.c_double), ctypes.POINTER(ctypes.c_double),
            ctypes.POINTER(ctypes.c_double), ctypes.POINTER(ctypes.c_double),
            ctypes.POINTER(ctypes.c_double),
        ]
        self.dll.evaluate_jacobian.argtypes = [
            ctypes.POINTER(ctypes.c_double), ctypes.POINTER(ctypes.c_double),
            ctypes.POINTER(ctypes.c_double), ctypes.POINTER(ctypes.c_double),
            ctypes.c_double, ctypes.POINTER(ctypes.c_double),
        ]
        self.dll.evaluate_vjp.argtypes = [
            ctypes.POINTER(ctypes.c_double), ctypes.POINTER(ctypes.c_double),
            ctypes.POINTER(ctypes.c_double), ctypes.POINTER(ctypes.c_double),
            ctypes.POINTER(ctypes.c_double), ctypes.POINTER(ctypes.c_double),
            ctypes.POINTER(ctypes.c_double), ctypes.POINTER(ctypes.c_double),
        ]
        
        self.dll.evaluate_residual.restype = None
        self.dll.evaluate_jacobian.restype = None
        self.dll.evaluate_vjp.restype = None

    def evaluate_residual(self, y: List[float], ydot: List[float], p: List[float], m: List[float]) -> List[float]:
        y_arr = (ctypes.c_double * self.n_states)(*y)
        ydot_arr = (ctypes.c_double * self.n_states)(*ydot)
        p_arr = (ctypes.c_double * len(p))(*p)
        m_arr = (ctypes.c_double * max(1, len(m)))(*m)
        res_arr = (ctypes.c_double * self.n_states)()
        self.dll.evaluate_residual(y_arr, ydot_arr, p_arr, m_arr, res_arr)
        return list(res_arr)

    def evaluate_jacobian(self, y: List[float], ydot: List[float], p: List[float], m: List[float], c_j: float) -> List[List[float]]:
        y_arr = (ctypes.c_double * self.n_states)(*y)
        ydot_arr = (ctypes.c_double * self.n_states)(*ydot)
        p_arr = (ctypes.c_double * len(p))(*p)
        m_arr = (ctypes.c_double * max(1, len(m)))(*m)
        jac_arr = (ctypes.c_double * (self.n_states * self.n_states))()
        
        self.dll.evaluate_jacobian(y_arr, ydot_arr, p_arr, m_arr, ctypes.c_double(c_j), jac_arr)
        
        # Correctly unpack the Fortran Column-Major dense layout required by SUNDIALS 
        # into a standard Row-Major Python 2D list for assertions.
        jac_2d = []
        for row in range(self.n_states):
            row_vals = []
            for col in range(self.n_states):
                # Column-major index math: (col * N) + row
                row_vals.append(jac_arr[col * self.n_states + row])
            jac_2d.append(row_vals)
            
        return jac_2d


class NativeCompiler:
    """Manages the Clang/LLVM toolchain invocation and caching of emitted C++ strings."""
    def __init__(self, cache_dir: str = None):
        self.cache_dir = cache_dir or os.path.join(tempfile.gettempdir(), "ion_flux_jit")
        os.makedirs(self.cache_dir, exist_ok=True)
        
        self.compiler_cmd = self._find_compiler()
        self.enzyme_plugin = self._find_enzyme_plugin()
        
        if not self.compiler_cmd:
            logging.warning("No compatible C++ compiler found. Native execution will fail.")

    def _find_compiler(self) -> str:
        if sys.platform == "darwin":
            for path in ["/opt/homebrew/opt/llvm/bin/clang++", "/usr/local/opt/llvm/bin/clang++"]:
                if os.path.exists(path): return path
        return shutil.which("clang++") or shutil.which("g++")

    def _find_enzyme_plugin(self) -> str:
        if sys.platform == "darwin":
            for base in ["/opt/homebrew/lib", "/usr/local/lib"]:
                matches = glob.glob(os.path.join(base, "ClangEnzyme*.dylib"))
                if matches: return matches[0]
        elif sys.platform == "linux":
            conda_prefix = os.environ.get("CONDA_PREFIX", "")
            if conda_prefix:
                matches = glob.glob(os.path.join(conda_prefix, "lib", "ClangEnzyme*.so"))
                if matches: return matches[0]
            for base in ["/usr/lib", "/usr/local/lib"]:
                matches = glob.glob(os.path.join(base, "ClangEnzyme*.so"))
                if matches: return matches[0]
        return ""

    def compile(self, cpp_source: str, n_states: int) -> NativeRuntime:
        if not self.compiler_cmd:
            raise RuntimeError("C++ toolchain is unavailable on this host.")

        source_hash = hashlib.sha256(cpp_source.encode('utf-8')).hexdigest()[:16]
        ext = ".dylib" if sys.platform == "darwin" else ".so"
        lib_name = f"lib_res_{source_hash}{ext}"
        lib_path = os.path.join(self.cache_dir, lib_name)
        
        if os.path.exists(lib_path):
            return NativeRuntime(lib_path, n_states)
            
        source_path = os.path.join(self.cache_dir, f"res_{source_hash}.cpp")
        with open(source_path, "w") as f:
            f.write(cpp_source)
            
        cmd = [self.compiler_cmd, "-O3", "-fPIC", "-shared", "-o", lib_path, source_path]
        
        if "#pragma omp" in cpp_source:
            cmd.append("-fopenmp")
            if sys.platform == "darwin":
                cmd.extend(["-lomp", "-Wl,-rpath,/opt/homebrew/lib", "-Wl,-rpath,/usr/local/lib"])
            elif sys.platform == "linux":
                # Bug 8 Fix: Statically links OpenMP to guarantee portable Serverless Cold-Starts
                cmd.extend(["-Wl,-Bstatic", "-lgomp", "-Wl,-Bdynamic"])
        
        if self.enzyme_plugin:
            cmd.insert(1, f"-fplugin={self.enzyme_plugin}")
            cmd.insert(2, "-DENZYME_ACTIVE")
        
        try:
            subprocess.run(cmd, check=True, capture_output=True, text=True)
        except subprocess.CalledProcessError as e:
            raise RuntimeError(f"Clang compilation failed. cmd: {' '.join(cmd)}\nstderr:\n{e.stderr}")
            
        return NativeRuntime(lib_path, n_states)