import os
import sys
import glob
import ctypes
import hashlib
import subprocess
import shutil
import logging
import tempfile
import uuid
from typing import List, Tuple

logger = logging.getLogger(__name__)

class NativeRuntime:
    """Wrapper around the C-ABI shared library generated by the JIT compiler."""
    def __init__(self, lib_path: str, n_states: int):
        self.lib_path = lib_path
        self.n_states = n_states
        
        try:
            self.dll = ctypes.CDLL(lib_path)
        except OSError as e:
            raise RuntimeError(f"Failed to load compiled binary at {lib_path}: {e}")

        # Bind OpenMP thread control if emitted
        if hasattr(self.dll, "set_spatial_threads"):
            self.dll.set_spatial_threads.argtypes = [ctypes.c_int]
            self.dll.set_spatial_threads.restype = None

        # Signature: void evaluate_residual(y, ydot, p, res)
        self.dll.evaluate_residual.argtypes = [
            ctypes.POINTER(ctypes.c_double), ctypes.POINTER(ctypes.c_double),
            ctypes.POINTER(ctypes.c_double), ctypes.POINTER(ctypes.c_double),
            ctypes.POINTER(ctypes.c_double),
        ]
        self.dll.evaluate_residual.restype = None
        
        if hasattr(self.dll, "evaluate_observables"):
            self.dll.evaluate_observables.argtypes = [
                ctypes.POINTER(ctypes.c_double), ctypes.POINTER(ctypes.c_double),
                ctypes.POINTER(ctypes.c_double), ctypes.POINTER(ctypes.c_double),
                ctypes.POINTER(ctypes.c_double),
            ]
            self.dll.evaluate_observables.restype = None

        # Signature: void evaluate_jacobian(y, ydot, p, c_j, jac_out)
        self.dll.evaluate_jacobian.argtypes = [
            ctypes.POINTER(ctypes.c_double), ctypes.POINTER(ctypes.c_double),
            ctypes.POINTER(ctypes.c_double), ctypes.POINTER(ctypes.c_double),
            ctypes.c_double, ctypes.POINTER(ctypes.c_double),
        ]
        self.dll.evaluate_jacobian.restype = None

        self.dll.evaluate_vjp.argtypes = [
            ctypes.POINTER(ctypes.c_double), ctypes.POINTER(ctypes.c_double),
            ctypes.POINTER(ctypes.c_double), ctypes.POINTER(ctypes.c_double),
            ctypes.POINTER(ctypes.c_double), ctypes.POINTER(ctypes.c_double),
            ctypes.POINTER(ctypes.c_double), ctypes.POINTER(ctypes.c_double),
        ]
        self.dll.evaluate_vjp.restype = None

    def set_spatial_threads(self, num_threads: int) -> None:
        if hasattr(self.dll, "set_spatial_threads"):
            self.dll.set_spatial_threads(num_threads)

    def evaluate_vjp(self, y: List[float], ydot: List[float], p: List[float], m: List[float], lambda_vec: List[float]) -> Tuple[List[float], List[float], List[float]]:
        y_arr = (ctypes.c_double * self.n_states)(*y)
        ydot_arr = (ctypes.c_double * self.n_states)(*ydot)
        p_arr = (ctypes.c_double * len(p))(*p)
        m_arr = (ctypes.c_double * len(m))(*m)
        lam_arr = (ctypes.c_double * self.n_states)(*lambda_vec)
        
        dp_out = (ctypes.c_double * len(p))()
        dy_out = (ctypes.c_double * self.n_states)()
        dydot_out = (ctypes.c_double * self.n_states)()
        
        self.dll.evaluate_vjp(y_arr, ydot_arr, p_arr, m_arr, lam_arr, dp_out, dy_out, dydot_out)
        return list(dp_out), list(dy_out), list(dydot_out)

    def evaluate_residual(self, y: List[float], ydot: List[float], p: List[float], m: List[float]) -> List[float]:
        y_arr = (ctypes.c_double * self.n_states)(*y)
        ydot_arr = (ctypes.c_double * self.n_states)(*ydot)
        p_arr = (ctypes.c_double * len(p))(*p)
        m_arr = (ctypes.c_double * len(m))(*m)
        res_arr = (ctypes.c_double * self.n_states)()
        
        self.dll.evaluate_residual(y_arr, ydot_arr, p_arr, m_arr, res_arr)
        return list(res_arr)
        
    def evaluate_observables(self, y: List[float], ydot: List[float], p: List[float], m: List[float], n_obs: int) -> List[float]:
        y_arr = (ctypes.c_double * self.n_states)(*y)
        ydot_arr = (ctypes.c_double * self.n_states)(*ydot)
        p_arr = (ctypes.c_double * len(p))(*p)
        m_arr = (ctypes.c_double * len(m))(*m)
        obs_arr = (ctypes.c_double * n_obs)()
        
        if hasattr(self.dll, "evaluate_observables"):
            self.dll.evaluate_observables(y_arr, ydot_arr, p_arr, m_arr, obs_arr)
        return list(obs_arr)

    def evaluate_jacobian(self, y: List[float], ydot: List[float], p: List[float], m: List[float], c_j: float) -> List[List[float]]:
        y_arr = (ctypes.c_double * self.n_states)(*y)
        ydot_arr = (ctypes.c_double * self.n_states)(*ydot)
        p_arr = (ctypes.c_double * len(p))(*p)
        m_arr = (ctypes.c_double * len(m))(*m)
        jac_arr = (ctypes.c_double * (self.n_states * self.n_states))()
        
        self.dll.evaluate_jacobian(y_arr, ydot_arr, p_arr, m_arr, ctypes.c_double(c_j), jac_arr)
        
        jac_2d = []
        for row in range(self.n_states):
            row_vals = []
            for col in range(self.n_states):
                row_vals.append(jac_arr[col * self.n_states + row])
            jac_2d.append(row_vals)
            
        return jac_2d


class NativeCompiler:
    """Manages the Clang/LLVM toolchain invocation and caching of emitted C++ strings."""
    def __init__(self, cache_dir: str = None):
        if cache_dir:
            self.cache_dir = cache_dir
            os.makedirs(self.cache_dir, exist_ok=True)
        else:
            self.cache_dir = tempfile.mkdtemp(prefix="ion_flux_jit_")
            
        self.bundled_toolchain_dir = os.path.expanduser("~/.cache/ion_flux/toolchain")
        
        self.compiler_cmd = self._find_bundled_compiler()
        self.enzyme_plugin = self._find_bundled_plugin()
        
        if not self.compiler_cmd:
            raise RuntimeError(
                "Hermetic C++ toolchain not found. Native execution requires the bundled LLVM/Enzyme toolchain. "
                "Execute `ion-flux install-toolchain` in your terminal to install it."
            )
        if not self.enzyme_plugin:
            raise RuntimeError(
                "Enzyme AD plugin not found. Exact analytical Jacobians require the bundled plugin. "
                "Execute `ion-flux install-toolchain` in your terminal to install it."
            )

    def _find_bundled_compiler(self) -> str:
        bundled_clang = os.path.join(self.bundled_toolchain_dir, "bin", "clang++")
        if os.path.exists(bundled_clang) and os.access(bundled_clang, os.X_OK):
            return bundled_clang
        return ""

    def _find_system_compiler(self) -> str:
        if sys.platform == "darwin":
            for path in ["/opt/homebrew/opt/llvm/bin/clang++", "/usr/local/opt/llvm/bin/clang++"]:
                if os.path.exists(path): return path
        return shutil.which("clang++") or shutil.which("g++") or ""

    def _find_bundled_plugin(self) -> str:
        ext = ".dylib" if sys.platform == "darwin" else ".so"
        bundled_matches = glob.glob(os.path.join(self.bundled_toolchain_dir, "lib", f"ClangEnzyme*{ext}"))
        if bundled_matches:
            return bundled_matches[0]
        return ""

    def _find_system_plugin(self) -> str:
        ext = ".dylib" if sys.platform == "darwin" else ".so"
        if sys.platform == "darwin":
            for base in ["/opt/homebrew/lib", "/usr/local/lib"]:
                matches = glob.glob(os.path.join(base, f"ClangEnzyme*{ext}"))
                if matches: return matches[0]
        elif sys.platform == "linux":
            conda_prefix = os.environ.get("CONDA_PREFIX", "")
            if conda_prefix:
                matches = glob.glob(os.path.join(conda_prefix, "lib", f"ClangEnzyme*{ext}"))
                if matches: return matches[0]
            for base in ["/usr/lib", "/usr/local/lib"]:
                matches = glob.glob(os.path.join(base, f"ClangEnzyme*{ext}"))
                if matches: return matches[0]
        return ""

    def compile(self, cpp_source: str, n_states: int) -> NativeRuntime:
        if not self.compiler_cmd:
            raise RuntimeError("C++ toolchain is unavailable on this host.")

        source_hash = hashlib.sha256(cpp_source.encode('utf-8')).hexdigest()[:16]
        ext = ".dylib" if sys.platform == "darwin" else ".so"
        lib_name = f"lib_res_{source_hash}{ext}"
        lib_path = os.path.join(self.cache_dir, lib_name)
        
        if os.path.exists(lib_path):
            return NativeRuntime(lib_path, n_states)
            
        tmp_uuid = uuid.uuid4().hex
        source_path = os.path.join(self.cache_dir, f"res_{source_hash}_{tmp_uuid}.cpp")
        tmp_lib_path = os.path.join(self.cache_dir, f"lib_{source_hash}_{tmp_uuid}{ext}")

        with open(source_path, "w") as f:
            f.write(cpp_source)
            
        def attempt_compile(compiler: str, plugin: str) -> bool:
            cmd = [compiler, "-O3", "-fPIC", "-shared", "-o", tmp_lib_path, source_path]
            
            if "#pragma omp" in cpp_source:
                cmd.append("-fopenmp")
                if sys.platform == "darwin":
                    cmd.extend(["-lomp", "-Wl,-rpath,/opt/homebrew/lib", "-Wl,-rpath,/usr/local/lib"])
                elif sys.platform == "linux":
                    cmd.extend(["-static-libgcc", "-static-libstdc++", "-Wl,-Bstatic", "-lgomp", "-Wl,-Bdynamic"])
            
            cmd.insert(1, f"-fplugin={plugin}")
            cmd.insert(2, "-DENZYME_ACTIVE")
            
            try:
                subprocess.run(cmd, check=True, capture_output=True, text=True)
                os.replace(tmp_lib_path, lib_path)
                return True
            except subprocess.CalledProcessError as e:
                self.last_error = f"cmd: {' '.join(cmd)}\nstderr:\n{e.stderr}"
                return False

        success = attempt_compile(self.compiler_cmd, self.enzyme_plugin)

        # Cleanup
        if os.path.exists(source_path):
            os.remove(source_path)
        if os.path.exists(tmp_lib_path):
            os.remove(tmp_lib_path)

        if not success:
            raise RuntimeError(f"Hermetic compilation failed.\n{getattr(self, 'last_error', 'Unknown error')}")
            
        return NativeRuntime(lib_path, n_states)