import os
import sys
import glob
import ctypes
import hashlib
import subprocess
import shutil
import logging
import tempfile
from typing import List

logger = logging.getLogger(__name__)

class NativeRuntime:
    """Wrapper around the C-ABI shared library generated by the JIT compiler."""
    def __init__(self, lib_path: str, n_states: int):
        self.lib_path = lib_path
        self.n_states = n_states
        
        try:
            self.dll = ctypes.CDLL(lib_path)
        except OSError as e:
            raise RuntimeError(f"Failed to load compiled binary at {lib_path}: {e}")

        self.dll.evaluate_residual.argtypes = [
            ctypes.POINTER(ctypes.c_double),
            ctypes.POINTER(ctypes.c_double),
            ctypes.POINTER(ctypes.c_double),
            ctypes.POINTER(ctypes.c_double),
        ]
        self.dll.evaluate_residual.restype = None

    def evaluate_residual(self, y: List[float], ydot: List[float], p: List[float]) -> List[float]:
        """Executes the natively compiled residual function directly on the CPU."""
        if len(y) != self.n_states or len(ydot) != self.n_states:
            raise ValueError(f"Expected state vectors of length {self.n_states}.")
            
        y_arr = (ctypes.c_double * self.n_states)(*y)
        ydot_arr = (ctypes.c_double * self.n_states)(*ydot)
        p_arr = (ctypes.c_double * len(p))(*p)
        res_arr = (ctypes.c_double * self.n_states)()
        
        self.dll.evaluate_residual(y_arr, ydot_arr, p_arr, res_arr)
        return list(res_arr)


class NativeCompiler:
    """Manages the Clang/LLVM toolchain invocation and caching of emitted C++ strings."""
    
    def __init__(self, cache_dir: str = None):
        self.cache_dir = cache_dir or os.path.join(tempfile.gettempdir(), "ion_flux_jit")
        os.makedirs(self.cache_dir, exist_ok=True)
        
        self.compiler_cmd = self._find_compiler()
        self.enzyme_plugin = self._find_enzyme_plugin()
        
        if not self.compiler_cmd:
            logging.warning("No compatible C++ compiler found. Native execution will fail.")

    def _find_compiler(self) -> str:
        """Locates the correct Clang binary, explicitly bypassing Apple Clang on macOS."""
        if sys.platform == "darwin":
            # Prioritize Homebrew LLVM (Apple Silicon then Intel paths)
            for path in ["/opt/homebrew/opt/llvm/bin/clang++", "/usr/local/opt/llvm/bin/clang++"]:
                if os.path.exists(path):
                    return path
        
        # Fallback for Linux / generic Conda environments
        return shutil.which("clang++") or shutil.which("g++")

    def _find_enzyme_plugin(self) -> str:
        """Locates the Enzyme dynamic library required for Auto-Diff passes."""
        if sys.platform == "darwin":
            for base in ["/opt/homebrew/lib", "/usr/local/lib"]:
                matches = glob.glob(os.path.join(base, "ClangEnzyme*.dylib"))
                if matches:
                    return matches[0]
                    
        elif sys.platform == "linux":
            # Search common Conda/Apt locations for Linux
            conda_prefix = os.environ.get("CONDA_PREFIX", "")
            if conda_prefix:
                matches = glob.glob(os.path.join(conda_prefix, "lib", "ClangEnzyme*.so"))
                if matches:
                    return matches[0]
            
            for base in ["/usr/lib", "/usr/local/lib"]:
                matches = glob.glob(os.path.join(base, "ClangEnzyme*.so"))
                if matches:
                    return matches[0]
                    
        return ""

    def compile(self, cpp_source: str, n_states: int) -> NativeRuntime:
        """
        Compiles the C++ string to a shared object (.so / .dylib).
        """
        if not self.compiler_cmd:
            raise RuntimeError("C++ toolchain is unavailable on this host.")

        source_hash = hashlib.sha256(cpp_source.encode('utf-8')).hexdigest()[:16]
        ext = ".dylib" if sys.platform == "darwin" else ".so"
        lib_name = f"lib_res_{source_hash}{ext}"
        lib_path = os.path.join(self.cache_dir, lib_name)
        
        if os.path.exists(lib_path):
            return NativeRuntime(lib_path, n_states)
            
        source_path = os.path.join(self.cache_dir, f"res_{source_hash}.cpp")
        with open(source_path, "w") as f:
            f.write(cpp_source)
            
        cmd = [self.compiler_cmd, "-O3", "-fPIC", "-shared", "-o", lib_path, source_path]
        
        # Inject the LLVM plugin if discovered
        if self.enzyme_plugin:
            cmd.insert(1, f"-fplugin={self.enzyme_plugin}")
        else:
            logging.warning("Enzyme plugin not found. Jacobian evaluation will fail at runtime.")
        
        try:
            subprocess.run(cmd, check=True, capture_output=True, text=True)
        except subprocess.CalledProcessError as e:
            raise RuntimeError(f"Clang compilation failed. cmd: {' '.join(cmd)}\nstderr:\n{e.stderr}")
            
        return NativeRuntime(lib_path, n_states)
