"""
Middle-End Codegen: ALE Moving Meshes

Validates the injection of Arbitrary Lagrangian-Eulerian (ALE) advection velocity
terms for moving boundaries (Stefan problems) and traps grid inversion conditions.
"""

import pytest
import ion_flux as fx
from ion_flux.runtime.engine import Engine

class HollowParticlePDE(fx.PDE):
    """
    Isolates Spherical Origin Singularity Logic.
    Models a hollow core particle where the inner radius > 0.
    """
    # Note the bounds: domain starts at 5 microns, NOT 0.
    r = fx.Domain(bounds=(5e-6, 10e-6), resolution=10, coord_sys="spherical", name="r")
    c = fx.State(domain=r, name="c")
    
    def math(self):
        return {
            "regions": {
                self.r: [ fx.dt(self.c) == fx.div(fx.grad(self.c)) ]
            },
            "boundaries": [
                self.c.left == 1.0, self.c.right == 0.0
            ]
        }

class ALEAdvectionPDE(fx.PDE):
    """
    Isolates Advective Instability in Moving Meshes (Stefan Problems).
    """
    x = fx.Domain(bounds=(0, 1), resolution=10, name="x")
    c = fx.State(domain=x, name="c")
    thickness = fx.State(domain=None, name="thickness")
    
    def math(self):
        return {
            "regions": {
                self.x: [ fx.dt(self.c) == fx.grad(self.c) ]
            },
            "boundaries": [
                self.x.right == self.thickness,  # Triggers ALE grid velocity injection
                self.c.left == 0.0, self.c.right == 0.0
            ],
            "global": [
                fx.dt(self.thickness) == 1.0, 
                self.thickness.t0 == 1.0
            ]
        }

@pytest.mark.xfail(reason="ALE needs some work.")
def test_hollow_particle_avoids_origin_singularity_logic():
    """
    X-Ray for Spherical L'Hopital constraints.
    Proves that a spherical domain bounding away from r=0 does not 
    blindly apply the 3*flux/dr symmetry condition at the first node.
    """
    model = HollowParticlePDE()
    engine = Engine(model=model, target="cpu", mock_execution=True)
    cpp = engine.cpp_source
    
    # In translator.py, it blindly writes: `((local_idx) == 0 ? (3.0 * ...)`
    # DIAGNOSTIC ASSERTION:
    # If the domain's lower bound > 0, the origin symmetry equation is mathematically invalid.
    # It must fall back to the standard expanded spherical divergence (grad + 2/r * c).
    # This test will FAIL until the topology checks `domain.bounds[0] == 0.0`.
    assert "((i) == 0 ? (3.0 *" not in cpp, (
        "Numerical Singularity Flaw: Compiler injected L'Hopital's symmetry "
        "condition at the left boundary of a hollow particle (r > 0)."
    )

@pytest.mark.xfail(reason="ALE needs some work.")    
def test_ale_advection_upwinding_stencil():
    """
    X-Ray for Advective Instability (Spurious Oscillations).
    Proves that the ALE grid velocity term uses a stable upwind scheme 
    rather than a centered difference scheme.
    """
    model = ALEAdvectionPDE()
    engine = Engine(model=model, target="cpu", mock_execution=True)
    cpp = engine.cpp_source
    
    # We locate the specific ALE injection generated by `ale.py`.
    # It currently emits: `(((y[idx+1]) - (y[idx-1])) / (2.0 * dx))`
    ale_term_segment = [line for line in cpp.split("\n") if "std::max(1e-12" in line]
    assert len(ale_term_segment) > 0, "Verify baseline: ALE advection term was injected."
    
    ale_line = ale_term_segment[0]
    
    # DIAGNOSTIC ASSERTION:
    # Centered differences for purely advective terms cause massive numerical ringing
    # when the mesh expands rapidly (high Cell-Peclet number).
    # The C++ should dynamically upwind based on the sign of the grid velocity:
    # `(v > 0 ? (y[i] - y[i-1])/dx : (y[i+1] - y[i])/dx)`
    # This test will FAIL until `ale.py` is refactored for upwinding.
    assert "v_mesh > 0" in ale_line or "2.0 *" not in ale_line, (
        "Numerical Instability Flaw: ALE advection uses a centered-difference "
        "stencil, guaranteeing spurious oscillations during rapid volume expansion."
    )